### ISSUE TITLE
Current time isn't update if AD panel is active

### ISSUE THREAD

**Issue by ytid** [adrewind/extension#3]
How to reproduce
--------------------

1. Open AD panel
2. Move mouse out of player
3. Pay attention to current time
![image](https://cloud.githubusercontent.com/assets/26866845/25481090/49abe710-2b54-11e7-9621-134175c19442.png)
4. Wait

**Comment by xakdog** [comment]
Interesting case. YouTube's `base.js` script will try to hide controls and stop counting time if:
* you move the mouse out of a player 
* you wait some time while not generating mouse moves

I'm unable to reach base.js code because it's inside of closure. I can't `stopPropagation` of events because it won't fix auto hide after some timeout. Usage of `pointer-events: none;` isn't possible in this case.
To fix it I can generate fake mouse moves or update value manually. As I've tested before fake mouse moves cause some twitching if you drag a playhead.
So... 
There's no other way. I need to update value manually.
